#!/bin/bash
#
#
#
echo "This will show you all the network interface configuration: using command ifconfig -a"
ifconfig -a 
#
#
echo "Press <enter>"
read   #this pause the script and you need to press <enter>

echo " This will ping google.com for 1 time: "
ping -c 1 google.com
#
#
echo "press <enter>"
read  #pauses script
#
#
echo "use command route -n to print route tables:"
route -n
#
#
echo " the command traceroute will trace hops to the next router to reach the destination:"
traceroute google.com
echo "press <enter>"
read
#
#
echo " this command traceroute -n <hostname> will use ip address only and not hostname: "
traceroute -n google.com
#
#
echo " the <host> command retrieved dns information: "
host google.com
nslookup -debug localhost
#
#
echo " below is the commnand to manually configure network address is 'ifconfig interface address netmask mask': "
ifconfig lo0 127.0.0.1/24 gw 192.168.2.1
#
#
echo " command to remove the default route 'route del -net default: '"
route del -net default
#
#
echo " command to add new route 'route add -net 192.168.2.0/24 gw 192.168.2.1
route add -net 192.168.2.0/24 gw 192.168.2.1
#
#
echo " display host files for dns: "
host /etc/hosts
#
#
echo " command to show dhcp leases for eth0:"
dhclient eth0
